### ISSUE TITLE
Error when calling get_credentials

### ISSUE THREAD

**Issue by muyiscoi** [greenbone/python-gvm#123]
### Expected behavior
Call `get_credentials` and get a response with all credentials
### Current behavior
call `get_credentials` and get a TypeError
```
Traceback (most recent call last):
  File "testvas.py", line 20, in <module>
    tasks = gmp.get_credentials()
  File "/usr/local/lib/python3.5/dist-packages/gvm/protocols/gmpv7.py", line 2188, in get_credentials
    return self.send_command(cmd)
  File "/usr/local/lib/python3.5/dist-packages/gvm/protocols/base.py", line 131, in send_command
    raise e
  File "/usr/local/lib/python3.5/dist-packages/gvm/protocols/base.py", line 127, in send_command
    self._send(cmd)
  File "/usr/local/lib/python3.5/dist-packages/gvm/protocols/base.py", line 63, in _send
    self._connection.send(data)
  File "/usr/local/lib/python3.5/dist-packages/gvm/connections.py", line 103, in send
    self._socket.sendall(data)
  File "/usr/lib/python3.5/ssl.py", line 888, in sendall
    amount = len(data)
TypeError: object of type 'XmlCommand' has no len()
```
### Steps to reproduce
1. Try to call `get_credentials`

Sample code
```python
from gvm.connections import TLSConnection
from gvm.protocols.latest import Gmp
from gvm.xml import pretty_print

connection = TLSConnection(hostname='127.0.0.1', port=9390)
gmp = Gmp(connection)

# Login
gmp.authenticate('admin', 'password')

# Get all credentials
creds = gmp.create_credentials()
pretty_print(creds)
```
### GVM versions
**gvm:** (gvmd --version)
```
root@openvas:/openvas# gvmd --version
Greenbone Vulnerability Manager 9.0+alpha~git-845cadcd-master
GIT revision 845cadcd-master
Manager DB revision 207
Copyright (C) 2010-2017 Greenbone Networks GmbH
License GPLv2+: GNU GPL version 2 or later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
**gvm-tools:** (gvm-cli --version)
```
gvm-cli 2.0.0.beta1. API version 1.0.0.beta2
```
### Environment
**Operating system:**
Ubuntu 18.04
**Installation method / source:** (packages, source installation)
source (git master)

### Logfiles
```
md   main:WARNING:2019-05-03 13h54.57 UTC:30775: read_from_client_tls: failed to read from client: The TLS connection was non-properly terminated.
md   main:WARNING:2019-05-03 13h55.38 UTC:30812: read_from_client_tls: failed to read from client: The TLS connection was non-properly terminated.
```

I've been able to run other functions successfully such as `create_credential` and `get_tasks` using the sample code above

**Comment by bjoernricks** [comment]
Already fixed in master with https://github.com/greenbone/python-gvm/pull/74
